name: Release

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    if: github.ref == 'refs/heads/master'
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create git tag
        id: tag
        uses: Digital-Udvikling/actions-calver@v0.1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-22.04
    needs: [ tag ]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to production registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/nickolaj-jepsen/web-vitals-collector:${{ needs.tag.outputs.tag }}
            ghcr.io/nickolaj-jepsen/web-vitals-collector:latest
  notify:
    runs-on: ubuntu-22.04
    needs: [ tag, build ]
    steps:
      - name: Create github release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ needs.tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
